# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(AGENT_INCLUDE_DIRS "/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/motion;/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/motion/include;/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/motion/runswift;/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/common;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/libnaoqi/include;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/boost/include/boost-1_55;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/cross/i686-aldebaran-linux-gnu/sysroot/usr/include;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/libnaoqi/include;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/boost/include/boost-1_55;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/cross/i686-aldebaran-linux-gnu/sysroot/usr/include;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/libnaoqi/include;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/boost/include/boost-1_55;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/cross/i686-aldebaran-linux-gnu/sysroot/usr/include" CACHE INTERNAL "" FORCE)
 
set(AGENT_LIBRARIES "general;/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/motion/build-atom/sdk/lib/naoqi/libagent.so" CACHE INTERNAL "" FORCE)
 
set(AGENT_TARGET "agent" CACHE INTERNAL "" FORCE)

set(AGENT_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(AGENT_DEPENDS "ALPROXIES;ALCOMMON;BOOST_SIGNALS;RTTOOLS;ALVALUE;ALERROR;QIMESSAGING;QITYPE;QI;BOOST_CHRONO;BOOST_FILESYSTEM;BOOST_PROGRAM_OPTIONS;BOOST_REGEX;DL;RT;BOOST;BOOST_DATE_TIME;BOOST_SYSTEM;BOOST_LOCALE;BOOST_THREAD;PTHREAD" CACHE INTERNAL "" FORCE)
 