# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(MOTION_INCLUDE_DIRS "/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/motion;/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/motion/include;/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/motion/runswift;/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/common;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/libnaoqi/include;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/boost/include/boost-1_55;/home/cris/nao/devtools/ctc-linux64-atom-2.1.4.13/cross/i686-aldebaran-linux-gnu/sysroot/usr/include" CACHE INTERNAL "" FORCE)
 
set(MOTION_LIBRARIES "general;/home/cris/nao/workspace/UnBeatables2016/UnBeatables/Challenge/motion/build-atom/sdk/lib/naoqi/libmotion.so" CACHE INTERNAL "" FORCE)
 
set(MOTION_TARGET "motion" CACHE INTERNAL "" FORCE)

set(MOTION_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(MOTION_DEPENDS "ALCOMMON;ALVALUE;ALERROR;QIMESSAGING;QITYPE;BOOST_DATE_TIME;BOOST_SIGNALS;RTTOOLS;QI;BOOST_CHRONO;BOOST_FILESYSTEM;BOOST_SYSTEM;BOOST_PROGRAM_OPTIONS;BOOST_REGEX;BOOST_LOCALE;BOOST_THREAD;PTHREAD;RT;DL;BOOST" CACHE INTERNAL "" FORCE)
 